#############################################################################
# Makefile for building: bin/hjs
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 15 15:02:49 2018
# Project:  hjs.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile hjs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -Iinc -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L./lib -lv8 -L./ -lcurl -lz -lQtWebKit -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gui.cpp \
		hio.cpp \
		bb.cpp \
		hh_shmem.c \
		hhprocess.cpp \
		hh_curl_util.cpp \
		bloom.c \
		rpi_sock.cpp \
		jsmn.c moc_mainwindow.cpp \
		moc_gui.cpp \
		qrc_hjs.cpp
OBJECTS       = main.o \
		mainwindow.o \
		gui.o \
		hio.o \
		bb.o \
		hh_shmem.o \
		hhprocess.o \
		hh_curl_util.o \
		bloom.o \
		rpi_sock.o \
		jsmn.o \
		moc_mainwindow.o \
		moc_gui.o \
		qrc_hjs.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hjs.pro
QMAKE_TARGET  = hjs
DESTDIR       = bin/
TARGET        = bin/hjs

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hjs.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile hjs.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile hjs.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hjs1.0.0 || $(MKDIR) .tmp/hjs1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hjs1.0.0/ && $(COPY_FILE) --parents mainwindow.h gui.h hio.h bb.h hh_shmem.h hhprocess.h hh_curl_util.h bloom.h rpi_sock.h jsmn.h .tmp/hjs1.0.0/ && $(COPY_FILE) --parents hjs.qrc .tmp/hjs1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp gui.cpp hio.cpp bb.cpp hh_shmem.c hhprocess.cpp hh_curl_util.cpp bloom.c rpi_sock.cpp jsmn.c .tmp/hjs1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/hjs1.0.0/ && (cd `dirname .tmp/hjs1.0.0` && $(TAR) hjs1.0.0.tar hjs1.0.0 && $(COMPRESS) hjs1.0.0.tar) && $(MOVE) `dirname .tmp/hjs1.0.0`/hjs1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hjs1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_gui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_gui.cpp
moc_mainwindow.cpp: hhprocess.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_gui.cpp: mainwindow.h \
		hhprocess.h \
		gui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) gui.h -o moc_gui.cpp

compiler_rcc_make_all: qrc_hjs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_hjs.cpp
qrc_hjs.cpp: hjs.qrc \
		hjs.gif
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name hjs hjs.qrc -o qrc_hjs.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		hhprocess.h \
		hh_curl_util.h \
		hio.h \
		gui.h \
		bb.h \
		hh_shmem.h \
		bloom.h \
		rpi_sock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		hhprocess.h \
		ui_mainwindow.h \
		gui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

gui.o: gui.cpp gui.h \
		mainwindow.h \
		hhprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o gui.cpp

hio.o: hio.cpp hio.h \
		mainwindow.h \
		hhprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hio.o hio.cpp

bb.o: bb.cpp bb.h \
		mainwindow.h \
		hhprocess.h \
		hh_shmem.h \
		hh_curl_util.h \
		bloom.h \
		rpi_sock.h \
		jsmn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bb.o bb.cpp

hh_shmem.o: hh_shmem.c hh_shmem.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o hh_shmem.o hh_shmem.c

hhprocess.o: hhprocess.cpp hhprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hhprocess.o hhprocess.cpp

hh_curl_util.o: hh_curl_util.cpp hh_curl_util.h \
		ua.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hh_curl_util.o hh_curl_util.cpp

bloom.o: bloom.c bloom.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o bloom.o bloom.c

rpi_sock.o: rpi_sock.cpp rpi_sock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rpi_sock.o rpi_sock.cpp

jsmn.o: jsmn.c jsmn.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jsmn.o jsmn.c

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_gui.o: moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gui.o moc_gui.cpp

qrc_hjs.o: qrc_hjs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_hjs.o qrc_hjs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

